version: '1.0.0.build{build}'
configuration:
- Debug
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  COVERALLS_REPO_TOKEN:
    secure: MVvYQBGULYonZ2Kl14jFKBLrrgrdurIi0iwQdUK6kiGsHegGjk+KMytjYL//6uWi
  OPENCOVER_CONSOLE: '%USERPROFILE%/.nuget/packages/OpenCover.4.6.519/tools/OpenCover.Console.exe'
  XUNIT_CONSOLE: '%USERPROFILE%/.nuget/packages/xunit.runner.console/2.1.0/tools/xunit.console.exe'
  OPENCOVER_TARGETDIR: './test/bin/Debug/netcoreapp1.0/'
  OPENCOVER_SEARCHDIRS: '%USERPROFILE%/.nuget/packages'
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
#- nuget restore -PackagesDirectory packages
- dotnet restore src/Console
- dotnet restore test
build_script:
- dotnet build "src/Console" -c %CONFIGURATION% --version-suffix %LABEL%
- dotnet build "test" -c %CONFIGURATION% --version-suffix %LABEL%
#- ls -l test/bin/Debug/netcoreapp1.0
#- cp packages/xunit.extensibility.execution.2.1.0/lib/net45/xunit.execution.desktop.dll test/bin/Debug/netcoreapp1.0
#- cp packages/xunit.extensibility.core.2.1.0/lib/dotnet/xunit.core.dll test/bin/Debug/netcoreapp1.0
#- cp packages/xunit.runner.visualstudio.2.1.0/build/_common/xunit.abstractions.dll test/bin/Debug/netcoreapp1.0
#- cp packages/xunit.assert.2.1.0/lib/dotnet/xunit.assert.dll test/bin/Debug/netcoreapp1.0
#- cp packages/System.Runtime.4.1.0/lib/net462/System.Runtime.dll test/bin/Debug/netcoreapp1.0
#- cp packages/System.Linq.4.1.0/lib/net463/System.Linq.dll test/bin/Debug/netcoreapp1.0
#- cp packages/System.Text.RegularExpressions.4.1.0/lib/net463/System.Text.RegularExpressions.dll test/bin/Debug/netcoreapp1.0
#- cp packages/System.Runtime.Extensions.4.1.0/lib/net462/System.Runtime.Extensions.dll test/bin/Debug/netcoreapp1.0
#- cp packages/System.Security.Cryptography.Algorithms.4.2.0/runtimes/win/lib/net461/System.Security.Cryptography.Algorithms.dll test/bin/Debug/netcoreapp1.0
#- ls -l test/bin/Debug/netcoreapp1.0
#- echo %CONFIGURATION%
after_build:
- dotnet publish "src/Console" -c %CONFIGURATION% --version-suffix %LABEL% -o artifacts\Console
- dotnet publish "test" -c %CONFIGURATION% --version-suffix %LABEL% -o artifacts\Console
test_script:
- cd test && dotnet test -c %CONFIGURATION% && cd ..
#test_script:
#- C:\users\appveyor\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe -target:C:\users\appveyor\.nuget/packages/xunit.runner.console/2.1.0/tools/xunit.console.exe "-targetargs:""test.dll"" -noshadow" -targetdir:./artifacts\console -filter:"+[AdventOfCode2016*]*" -output:opencoverCoverage.xml -returntargetcode -skipautoprops -log:ALL -searchdirs:C:\users\appveyor\.nuget\packages 
#- ps: $env:OPENCOVER_CONSOLE -register:user -target:$env:XUNIT_CONSOLE "-targetargs:""test.dll"" -noshadow -appveyor -parallel none -xml results.xml" -targetdir:$env:OPENCOVER_TARGETDIR -filter:"+[AdventOfCode2016*]*" -output:opencoverCoverage.xml -returntargetcode -skipautoprops -log:ALL -searchdirs:$env:OPENCOVER_SEARCHDIRS
#- ps: ./packages/coveralls.net.0.6.0/tools/csmacnz.Coveralls.exe --opencover -i ./opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
#test:
#  assemblies:
#    - 'test/bin/Debug/netcoreapp1.0/test.dll'
artifacts:
- path: artifacts\**\*.*
# cache:
# - '%USERPROFILE%\.nuget\packages'
# on_finish: # Run the demo to show that it works
# - dotnet artifacts\Console\Console.dll